// Code generated by "tfplugingen -gen datasource -type dataHTTP"; DO NOT EDIT.

package provider

import (
	terraformpluginsdk "github.com/hashicorp/terraform-plugin-sdk"
	cty "github.com/zclconf/go-cty/cty"
)

func (r *dataHTTP) Schema() terraformpluginsdk.Schema {
	return terraformpluginsdk.Schema{Block: terraformpluginsdk.Block{Attributes: []terraformpluginsdk.Attribute{terraformpluginsdk.Attribute{
		Computed: false,
		Name:     "url",
		Optional: false,
		Required: true,
		Type:     cty.String,
	}, terraformpluginsdk.Attribute{
		Computed: false,
		Name:     "request_headers",
		Optional: true,
		Required: false,
		Type:     cty.Map(cty.String),
	}, terraformpluginsdk.Attribute{
		Computed: true,
		Name:     "body",
		Optional: false,
		Required: false,
		Type:     cty.String,
	}}}}
}
func (r *dataHTTP) PopulateConfig(conf cty.Value) error {
	var v cty.Value
	v = conf.GetAttr("url")
	if v.IsNull() {
		r.URL = ""
	} else {
		r.URL = ""
	}
	v = conf.GetAttr("request_headers")
	if v.IsNull() {
		r.RequestHeaders = nil
	} else {
		r.RequestHeaders = nil
	}
	v = conf.GetAttr("body")
	if v.IsNull() {
		r.Body = ""
	} else {
		r.Body = ""
	}
	return nil
}
