// Code generated by "tfplugingen -gen provider -type provider"; DO NOT EDIT.

package provider

import (
	"fmt"
	terraformpluginsdk "github.com/hashicorp/terraform-plugin-sdk"
	cty "github.com/zclconf/go-cty/cty"
)

func (r *provider) Schema() terraformpluginsdk.Schema {
	return terraformpluginsdk.Schema{Block: terraformpluginsdk.Block{Attributes: []terraformpluginsdk.Attribute{terraformpluginsdk.Attribute{
		Computed: false,
		Name:     "request_headers",
		Optional: true,
		Required: false,
		Type:     cty.Map(cty.String),
	}}}}
}
func (r *provider) PopulateConfig(conf cty.Value) error {
	var v cty.Value
	v = conf.GetAttr("request_headers")
	if v.IsNull() {
		r.RequestHeaders = nil
	} else {
		vm := v.AsValueMap()
		r.RequestHeaders = make(map[string]string, len(vm))
		for k, vmv := range vm {
			r.RequestHeaders[k] = vmv.AsString()
		}
	}
	return nil
}
func (p *provider) DataSourceFactory(typeName string) terraformpluginsdk.DataSource {
	switch typeName {
	case "http":
		return &dataHTTP{provider: p}
	}
	panic(fmt.Sprintf("datasource %s unexpected", typeName))
}
func (p *provider) DataSourceSchemas() map[string]terraformpluginsdk.Schema {
	return map[string]terraformpluginsdk.Schema{"http": p.DataSourceFactory("http").Schema()}
}
func (p *provider) ResourceFactory(typeName string) terraformpluginsdk.Resource {
	panic(fmt.Sprintf("resource %s unexpected", typeName))
}
func (p *provider) ResourceSchemas() map[string]terraformpluginsdk.Schema {
	return map[string]terraformpluginsdk.Schema{}
}
