// Code generated by "tfplugingen -gen provider -type provider"; DO NOT EDIT.

package provider

import (
	terraformpluginsdk "github.com/hashicorp/terraform-plugin-sdk"
	cty "github.com/zclconf/go-cty/cty"
)

func (r *provider) Schema() terraformpluginsdk.Schema {
	return terraformpluginsdk.Schema{Block: terraformpluginsdk.Block{Attributes: []terraformpluginsdk.Attribute{terraformpluginsdk.Attribute{
		Computed: false,
		Name:     "request_headers",
		Optional: true,
		Required: false,
		Type:     cty.Map(cty.String),
	}}}}
}
func (r *provider) PopulateConfig(conf cty.Value) error {
	var v cty.Value
	v = conf.GetAttr("request_headers")
	if v.IsNull() {
		r.RequestHeaders = nil
	} else {
		vm := v.AsValueMap()
		r.RequestHeaders = make(map[string]string, len(vm))
		for k, vmv := range vm {
			r.RequestHeaders[k] = vmv.AsString()
		}
	}
	return nil
}
